### ISSUE TITLE
LibWeb: DOM Elements colliding when using flex-wrap and changing child element margins

### ISSUE THREAD

**Issue by kemzeb** [SerenityOS/serenity#15486]
Messing with the CSS of `Base/res/html/misc/new-tab.html`, I found that adding the `flex-wrap: wrap` declaration to the `#search-buttons` selector and having its child elements have margins >= 4px would cause the `<form>` element and the closest `<p>` element to collide with one another:
![Screenshot 2022-10-05 143843](https://user-images.githubusercontent.com/60799661/194168910-2922f27e-b87b-48a0-87b4-3008cae8acc0.png)
The CSS changes made in `new-tab.html`:
```css
        #search-buttons {
            display: flex;
            flex-wrap: wrap; /* added this */
            justify-content: center;  /* space-between -> center (tested using both values, collision still occurs) */
            align-items: center;
        }

        #search-buttons > button { /* added this selector to change child element margins */
            margin: 4px;
        }
```
Just for reference, this is how it is represented in ***Firefox*** (had file pathing issues getting Ladybird to appear; I'm new to WSL):
![Screenshot 2022-10-05 152227](https://user-images.githubusercontent.com/60799661/194174759-6ba794a2-f40a-40d2-8304-add6933e8ea1.png)
