### ISSUE TITLE
LibWeb: Crash on CSS animation with background-position

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#23367]
Repro:

```css
<!doctype html><style>    
    div {    
        animation: foo 10s infinite linear;    
    }    
    @keyframes foo {    
        0% { background-position: 0% 50%; }    
        100% { background-position: 0% 50%; }    
    }                                              
</style><div>
```

```
VERIFICATION FAILED: false at /home/kling/src/serenity/Build/lagom/Userland/Libraries/LibWeb/CSS/PropertyID.cpp:1990
/home/kling/src/serenity/Build/lagom/lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x7f4c95d4a05f]
/home/kling/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::CSS::animation_type_from_longhand_property(Web::CSS::PropertyID) 0x60) [0x7f4c969e87f0]
/home/kling/src/serenity/Build/lagom/lib/liblagom-web.so.0 Web::CSS::StyleComputer::collect_animation_into(JS::NonnullGCPtr<Web::Animations::KeyframeEffect>, Web::CSS::StyleProperties&) const 0x5cf) [0x7f4c9655011f]
```

cc @mattco98
