### ISSUE TITLE
LibWeb: Images on OpenAI customer stories don't load fallback after HTTP 400

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#23939]
On this website, some images don't load: https://openai.com/customer-stories/jetbrains

We get the following debug messages:
```
462712.142 WebContent(2244576): ResourceLoader: Failed load of: "https://images.openai.com/blob/46d99f08-c849-4c73-b8ad-6896102abc4c/Frame1532576563.png?trim=38,0,100,0&width=1919&height=1923", Error: Load failed: 400, Duration: 321ms
462712.146 WebContent(2244576): ResourceLoader: Failed load of: "https://images.openai.com/blob/8fe8a156-003e-43bf-9d00-a5374df297d5/JetBrains_AI_1280x7202x.png?trim=0,0,0,0&width=1919&height=1079", Error: Load failed: 400, Duration: 321ms
462712.146 WebContent(2244576): ResourceLoader: Failed load of: "https://images.openai.com/blob/a74f7081-d2b9-4990-bd44-e4c25d49641e/vlad_tankov_jetbrains_ai.png?trim=0,0,0,0&width=1919&height=2880", Error: Load failed: 400, Duration: 321ms
```

Testing with Firefox, we see that they attempt these loads as well, and also get HTTP 400. But somehow they fall back to loading other images.

**Comment by trflynn89** [comment]
Seems like a CSS issue. The image itself does load, but ends up with a height of 0.

Its immediate parent is a div with a CSS class called `ratio`. If I remove that class with the inspector, the image shows. That CSS class is:
```css
.ratio {
	--ratio: 100%;
	display: block;
	position: relative;
	overflow: hidden;
}
```

In Firefox, if I toggle off the `--ratio: 100%` var, then the page renders like we do in Ladybird. Maybe we're not picking up this variable?

CC @AtkinsSJ

**Comment by trflynn89** [comment]
Actually it's an issue with `attr`. There's a `::before` rule on that `ratio` class:
```css
.ratio:before {
    content: attr(\1f47b);
    display: block;
    width: 100%;
    height: 0;
    padding-bottom: var(--ratio);
}
```

If I change that `content: attr(\1f47b)` (which is 👻) to `content: ' '`, the image renders:
![Screenshot_20240416_104924](https://github.com/SerenityOS/serenity/assets/5600524/6e7c44c0-6139-49e8-9f92-9dbe03cbc1b8)
